---
params:
  vsphere_cpu: 2
  vsphere_ram: 4096
  vsphere_disk: 40960

  vsphere_network: (( param "Enter the vSphere network name" ))
  vsphere_disk_type: (( param "Enthe the vSphere persistent disk type for disk pool" ))
