params: 
  consul_instances:      1
  haproxy_instances:     1
  nats_instances:        1
  mysql_instances:       1
  postgres_instances:    1
  blobstore_instances:   1
  uaa_instances:         1
  api_instances:         1
  cc-worker_instances:   1
  cc-clock_instances:    1
  doppler_instances:     1
  loggregator_instances: 1
  router_instances:      1
  bbs_instances:         1
  diego_instances:       1
  access_instances:      1
  cell_instances:        1
