- name: stemcell
  path: /resource_pools/name=vms/stemcell?
  type: replace
  value:
    sha1: af4cd6a4285c622b101dda1ea5980c46c1052934
    url: https://storage.googleapis.com/bosh-core-stemcells/1.192/bosh-stemcell-1.192-warden-boshlite-ubuntu-bionic-go_agent.tgz
