- name: stemcell
  path: /resource_pools/name=vms/stemcell?
  type: replace
  value:
    sha1: 22a3efed13dbd16f8949c5a03a1e628e1fb1c16d
    url: https://storage.googleapis.com/bosh-core-stemcells/1.204/bosh-stemcell-1.204-warden-boshlite-ubuntu-bionic-go_agent.tgz
