- name: stemcell
  path: /resource_pools/name=vms/stemcell?
  type: replace
  value:
    sha1: c45bf6a399e861e26cbc16f3c7d4bef4941c15b2
    url: https://storage.googleapis.com/bosh-core-stemcells/1.174/bosh-stemcell-1.174-warden-boshlite-ubuntu-bionic-go_agent.tgz
