#!/bin/bash

export BAT_STEMCELL="$(pwd)/stemcell/stemcell.tgz"
export BAT_DEPLOYMENT_SPEC="$(pwd)/git-ci/ci/bats-${BAT_INFRASTRUCTURE}.yml"
export BAT_BOSH_CLI=bosh
# DNS host or IP where BOSH-controlled PowerDNS server is running, which is required for the DNS tests. For example, if BAT is being run against a MicroBOSH then this value will be the same as BAT_DIRECTOR
export BAT_NETWORKING=manual

# the path to ssh key, used by OS specs to ssh into BOSH VMs
export BAT_PRIVATE_KEY="$(pwd)/dummy"
export BOSH_OS_BATS=false


safe target da-vault "$VAULT_URI" -k
echo "$VAULT_TOKEN" | safe auth token
safe read secret/handshake

exodus="$(safe read secret/exodus/ci-${BAT_INFRASTRUCTURE}-bats/bosh | spruce json)"
export BOSH_ENVIRONMENT="$(jq -r .url <<<"$exodus")"
export BOSH_CA_CERT="$(jq -r .ca_cert <<<"$exodus")"
export BOSH_CLIENT="$(jq -r .admin_username <<<"$exodus")"
export BOSH_CLIENT_SECRET="$(jq -r .admin_password <<<"$exodus")"

if [[ "$BAT_INFRASTRUCTURE" == 'gcp' ]] ; then
  export BAT_INFRASTRUCTURE='google' # because, consistency...
fi

gem install bundler
cd bats
bundle install
# NOTE!: adding tags will exlude component.
bundle exec rspec spec \
  --tag ~vip_networking \
  --tag ~dynamic_networking \
  --tag ~root_partition \
  --tag ~raw_ephemeral_storage \
  --tag ~multiple_manual_networks
