#!/bin/bash -
set -ue
base_dir="$(cd "$(dirname "$0")/.." && pwd)"
mkdir -p "${base_dir}/pipeline/upstream/"

_lookup() {
 echo "${1}" | base64 --decode | jq -re "${2}"
}

# Read upstream.yml
update_group=()
upstream_details="$(spruce json "${base_dir}/settings.yml" | jq -r '.meta.upstream.bosh_releases//[] | .[] | @base64')"
upstream_manifest="$(spruce merge "$base_dir/pipeline/base.yml" "$base_dir/settings.yml" | spruce json | jq -r '.meta.upstream.manifest//{} | @base64')"

# Support upstream manifests
package="$(_lookup "$upstream_manifest" '.package')" || true
if [[ -n "$package" && "$package" != "null" ]] ; then

  job="update-$package-manifest"
  #job="upstream-manifest" # Temporary name to match existing pipeline

  update_group+=( "$job" )
  cat <<EOF > "$base_dir/pipeline/upstream/upstream-manifest-job.yml"
jobs:
- name: $job
  public: true
  serial: true
  plan:
  - do:
    - in_parallel:
      - { get: git, trigger: false }
      - { get: git-ci, trigger: false}
      - { get: upstream-manifest, trigger: true }
    - task: $job
      file: git-ci/ci/tasks/get-latest-upstream-manifest.yml
      params:
        GIT_EMAIL:        (( grab meta.git.email ))
        GIT_NAME:         (( grab meta.git.name ))
        UPSTREAM_PATH:    (( grab meta.upstream.manifest.path ))
        UPSTREAM_REPO:    (( grab meta.upstream.manifest.repo ))
    - put: git
      params:
        merge: true
        repository: git
    on_success:
      put: notify
      params:
        topic:   (( concat meta.shout.topic "-\$BUILD_JOB_NAME" ))
        message: tests job '\$BUILD_JOB_NAME' succeeded.
        ok:      yes
        link:    (( grab meta.shout.links.build ))
    on_failure:
      put: notify
      params:
        topic:   (( concat meta.shout.topic "-\$BUILD_JOB_NAME" ))
        message: tests job '\$BUILD_JOB_NAME' failed.
        ok:      no
        link:    (( grab meta.shout.links.build ))
EOF
	cp "$base_dir/pipeline/optional-resources/upstream-manifest.yml" "$base_dir/pipeline/upstream/upstream-manifest-resource.yml"
fi

# For each release in upstream.yml,
for release in $upstream_details ; do
  name="$(_lookup "$release" .name)"
  type="$(_lookup "$release" '.type//"bosh-io-release"')"
  path="$(_lookup "$release" '.path//"manifests/releases/'"$name"'.yml"')"
  repo="$(_lookup "$release" '.repository')"
  if [[ $type == 'bosh-io-release' ]] ; then
    source=$'\n'"      repository: $repo";
  elif [[ $type == 'github-release' ]] ; then
    owner="$(_lookup "$release" '.owner//""')"
    if [[ -z "$owner" && "$repo" =~ / ]] ; then
      owner="${repo%%/*}"
      repo="${repo#*/}"
    fi
    source=$'\n'"      repository: $repo"$'\n'"      owner: $owner";

    token="$(_lookup "$release" '.access_token//""')"
    if [[ -n "$token" ]] ; then
      source="$source"$'\n      access_token: "'"$token"'"'
    fi
  else
    echo >&2 "Unknown resource type for $name upstream release: $type"
    echo >&2 "Expecting one of: bosh-io-release, github-release"
    echo >&2 "Update upstream.bosh-releases configuration in ci/settings.yml"
    exit 1
  fi
  job="update-${name}-release"
  release="${name}-release"

  update_group+=( "$job" )

  cat <<EOF >> "$base_dir/pipeline/upstream/update-${name}-release-job.yml"
jobs:
- (( append ))
- name: $job
  public: false
  serial: true
  serial_groups: [upstream-releases]
  plan:
  - do:
    - in_parallel:
      - { get: git,    trigger: false }
      - { get: git-ci, trigger: false }
      - get: $release
        trigger: true
        params:
          tarball: false
    - task: $job
      file: git-ci/ci/tasks/update-release.yml
      input_mapping: {bosh-release: $release}
      params:
        RELEASE_NAME:  $name
        RELEASE_PATH:  $path
        BRANCH:        (( grab meta.github.branch ))
        GIT_EMAIL:     (( grab meta.git.email ))
        GIT_NAME:      (( grab meta.git.name ))
    - put: git
      params:
        merge: true
        repository: git

resources:
  - (( append ))
  - name: $release
    type: $type
    check_every: 24h
    source: $source
EOF

done
group_file="$base_dir/pipeline/upstream/_update_group.yml"
if [[ "${#update_group[@]}" -gt 0 ]] ; then
  (
  echo "groups:"
  echo "- (( merge on name ))"
  echo "- name: upstream"
  echo "  jobs:"
  echo "  - (( append ))"
  for job in ${update_group[@]+"${update_group[@]}"} ; do
    echo "  - $job"
  done
  ) > "$group_file"
elif [[ -f "$group_file" ]] ; then
  rm -f "$group_file"
fi
