#!/bin/bash
dir=$(dirname $0)
( 
cd $dir/../.. &&
out="$(eval "spruce merge --skip-eval $( \
  grep -rl '^releases:' manifests/ \
  | sed -e "s/\\(.*\\)/<(spruce json \\1 | jq -r '{releases: .releases}')/" |tr "\n" " " \
  ) | spruce json | jq -r ." )"

echo "$out" \
  | jq -r 'reduce .releases[] as {$name, $url, $sha1, $version} ({core: [], buildpacks: []};
    ($url 
      | if ($url | test("https?://bosh.io")) then 
          ($url | sub("^.*/d/";"https://") | sub("\\?v=.*$";"/releases/tag/${version}"))
        elif ($url | test("https?://github.com")) then
          ($url | sub("^.*http";"http") | sub("/download/.*$";"/tag/${version}"))
        else
          $url
        end
      ) as $notes |
      if ($name | test("-buildpack$")) then 
        (.buildpacks += [{name: ($name|sub("-buildpack";"")),$notes}])
      else 
        (.core += [{$name,$notes}])
      end
    )' | spruce merge --skip-eval > ci/upstream.yml
)
