#!/usr/bin/perl
use strict;
use warnings;
use JSON::PP qw/decode_json/;

my $rc = 0;
my $data = decode_json(do { local $/; <> });
for my $r (@{$data->{releases} || []}) {
	chomp(my $sha1 = `curl -Lsk "$r->{url}" | sha1sum`);
	$sha1 =~ s/ .*//;

	if ($r->{sha1} eq $sha1) {
		print "[ok] $r->{name} (v$r->{version}) sha1 checkums are correct.\n";
	} else {
		print "[!!] $r->{name} (v$r->{version}) sha1 checkums are INCORRECT.\n";
		print "[!!]     the kit has '$r->{sha1}' (wrong)\n";
		print "[!!]    actually got '$sha1' (correct)\n";
		$rc = 1;
	}
}

if ($rc) {
	print "\n[31m[!!] sha1 check failed.[0m\n";
} else {
	print "\n[32m[ok] sha1 check passed.[0m\n";
}
exit $rc;
