#!/bin/bash
set -eu

# Resource Directories
export REPO_ROOT="git"
export TAG_ROOT="git-latest-tag"
export CI_ROOT="git-ci"
export DEPLOY_ENV="${DEPLOY_ENV:-"ci-baseline"}"
export VERSION_FROM="version/number"
export GIT_NAME="${GIT_NAME:-"Stark & Wayne CI Bot"}"
export GIT_EMAIL="${GIT_EMAIL:-"ci@starkandwayne.com"}"
OUTPUT_ROOT="spec-check"

header() {
  echo
  echo "================================================================================"
  echo "$1"
  echo "--------------------------------------------------------------------------------"
  echo
}

bail() {
  echo >&2 "$*  Did you misconfigure Concourse?"
  exit 2
}
test -n "${KIT_SHORTNAME:-}"      || bail "KIT_SHORTNAME must be set to the short name of this kit."
test -n "${VAULT_URI:-}"          || bail "VAULT_URI must be set to an address for connecting to Vault."
test -n "${VAULT_TOKEN:-}"        || bail "VAULT_TOKEN must be set to something; it will be used for connecting to Vault."

if [[ "${DEPLOY_ENV#ci-}" != 'proto' ]] ; then
  test -n "${BOSH_ENVIRONMENT:-}"   || bail "BOSH_ENVIRONMENT must be set in order to connect to BOSH director"
  test -n "${BOSH_CA_CERT:-}"       || bail "BOSH_CA_CERT must be set in order to connect to BOSH director"
  test -n "${BOSH_CLIENT:-}"        || bail "BOSH_CLIENT must be set in order to connect to BOSH director"
  test -n "${BOSH_CLIENT_SECRET:-}" || bail "BOSH_CLIENT_SECRET must be set in order to connect to BOSH director"
  export GENESIS_BOSH_ENVIRONMENT="$BOSH_ENVIRONMENT"
fi

header "Setting up git..."
git config --global user.name  "$GIT_NAME"
git config --global user.email "$GIT_EMAIL"

header "Connecting to vault..."
safe target da-vault "$VAULT_URI" -k
echo "$VAULT_TOKEN" | safe auth token
safe read secret/handshake

VERSION="$(cat "${TAG_ROOT}/.git/ref" | sed -e 's/^v//')"
header "Setting up initial Genesis deployment directory for $KIT_SHORTNAME v$VERSION..."
rm -rf work/*; mkdir -p work/
genesis -v
genesis -C work/ init -k "$KIT_SHORTNAME/$VERSION" --vault da-vault

header "Copying test environment YAMLs from $CI_ROOT/ci/envs..."
CI_PATH="$(cd "${CI_ROOT}" && pwd)"
cp -av "$CI_PATH"/ci/envs/*.yml "work/${KIT_SHORTNAME}-deployments/"
test -f "work/${KIT_SHORTNAME}-deployments/$DEPLOY_ENV.yml" || \
  bail "Environment $DEPLOY_ENV.yml was not found in the $CI_ROOT ci/envs/ directory"
cat <<EOF > "work/${KIT_SHORTNAME}-deployments/ci.yml"
---
kit:
  name: $KIT_SHORTNAME
  version: $VERSION
EOF
export PATH="$PATH:$CI_PATH/ci/scripts"

echo $'\n'"Handing off to ${CI_ROOT}/ci/test..."
cd "work/${KIT_SHORTNAME}-deployments"
BOSH=bosh "$CI_PATH/ci/scripts/test"

echo
echo "SUCCESS"
exit 0
