#!/bin/bash
#
# ci/scripts/testflight
#
# Script for testing a Genesis Kit
#
# author:  James Hunt <james@niftylogic.com>
# created: 2018-01-23
#

set -eu

: ${BOSH_ENVIRONMENT:?required}
: ${BOSH_CA_CERT:?required}
: ${BOSH_CLIENT:?required}
: ${BOSH_CLIENT_SECRET:?required}
: ${VAULT_URI:?required}
: ${VAULT_TOKEN:?required}
: ${KIT_SHORTNAME:?required}

header() {
	echo
	echo "###############################################"
	echo
	echo $*
	echo
}

header "Setting up git..."
git config --global user.name  "$GIT_NAME"
git config --global user.email "$GIT_EMAIL"

safe target da-vault "$VAULT_URI" -k
echo "$VAULT_TOKEN" | safe auth token
safe read secret/handshake

header "Setting up Genesis *-deployments/ directory..."
rm -rf work/; mkdir -p work/
genesis -C work/ init -L ../kit/ ${KIT_SHORTNAME}

header "Copying test environment YAMLs from \$kit/ci/envs..."
cp -av kit/ci/envs/*.yml work/${KIT_SHORTNAME}-deployments/

header "Handing off to \$kit/ci/test..."
cd work/${KIT_SHORTNAME}-deployments
export GENESIS_BOSH_ENVIRONMENT=$BOSH_ENVIRONMENT
BOSH=bosh2 ../../kit/ci/test

echo
echo "SUCCESS"
exit 0
