#!/bin/bash
set -eu

DEPLOY_ENV=${DEPLOY_ENV:-"ci-baseline"}
SKIP_FRESH=${SKIP_FRESH:-"false"}
SKIP_REPLACE_SECRETS=${SKIP_REPLACE_SECRETS:-"false"}
SKIP_DEPLOY=${SKIP_DEPLOY:-"false"}
SKIP_SMOKE_TESTS=${SKIP_SMOKE_TESTS:-"false"}
SKIP_CLEAN=${SKIP_CLEAN:-"false"}

header() {
  echo
  echo "================================================================================"
  echo "$1"
  echo "--------------------------------------------------------------------------------"
  echo
}

has_feature() {
	genesis lookup "$1" kit.features 2>/dev/null | jq -e --arg feature "$2" '. | index($feature)' >/dev/null
}

is_proto() {
	has_feature $1 'proto' # This will need to be changed in v2.8.0
}

cleanup_environment() {
	env="$1"
	if [[ -f .genesis/manifests/$env-state.yml ]] ; then
		header "Preparing to delete proto environment $env"
		echo "Generating reference manifest..."
		genesis manifest "$env" --no-redact > manifest.yml 2>/dev/null
		echo $'\n'"Building BOSH variables file..."
		genesis lookup --merged "${env}" bosh-variables > vars.yml 2>/dev/null
		echo $'\n'"$env state file:"
		echo "----------------->8------------------"
		cat ".genesis/manifests/$env-state.yml"
		echo "----------------->8------------------"
		header "Deleting $DEPLOY_ENV environment..."
		$BOSH delete-env --state ".genesis/manifests/$env-state.yml" --vars-file vars.yml manifest.yml
		rm manifest.yml
		rm vars.yml
	else
		echo "Cannot clean up previous $env environment - no state file found"
	fi
}

cleanup_deployment() {
	deployment="$1"
	echo "> deleting ${deployment}"
	$BOSH -n -d "${deployment}" delete-deployment

	for disk in $($BOSH disks --orphaned | grep "${deployment}" | awk '{print $1}'); do
		echo "	- removing disk $disk"
		$BOSH -n delete-disk "$disk"
	done
}

cleanup() {
	for deployment in "$@"; do
		if is_proto "$deployment" ; then
			cleanup_environment "$deployment"
		else
			(
				eval "$(genesis bosh --connect "${deployment}")"
				cleanup_deployment "$deployment-${KIT_SHORTNAME}"
			)
		fi
	done
}

header "Pre-test Cleanup"
if [[ "$SKIP_FRESH" == "false" ]]; then
	echo "Deleting any previous deploy"
	cleanup "${DEPLOY_ENV}"
else
	echo "Skipping cleaning up from any previous deploy"
fi

cat <<EOF > get-env.pl
#!/usr/bin/env perl
use lib "$ENV{HOME}/.geese/lib";
use JSON::PP qw/encode_json/;
print encode_json(\%ENV);
EOF
chmod get-env.pl
vault_path="$(genesis sh "${DEPLOY_ENV}" -s "$(pwd)/get-env.pl" | grep '^{' | jq -r '.GENESIS_SECRETS_BASE')"
vault_path="${vault_path%/}" # trim any trailing slash

if [[ "$SKIP_REPLACE_SECRETS" == "false" ]] ; then
	safe rm -rf "$vault_path"
  if [[ -n "$SECRETS_SEED_DATA" ]] ; then
    echo "$SECRETS_SEED_DATA" | sed -e 's#"\${GENESIS_SECRETS_BASE}/*#"'"$vault_path"'/#g' | safe import
  fi
else
	echo "Skipping replacing secrets"
fi
safe_target_orig="$(safe target --json | jq -r .name)"

if [[ "$SKIP_DEPLOY" == "false" ]]; then
	header "Deploying ${DEPLOY_ENV} environment to verify functionality..."
	genesis "do" "${DEPLOY_ENV}" -- list
	genesis add-secrets "${DEPLOY_ENV}"
	genesis deploy -y "${DEPLOY_ENV}"

	if [[ -f .genesis/manifests/${DEPLOY_ENV}-state.yml ]] ; then
		echo $'\n'"${DEPLOY_ENV} state file:"
		echo "----------------->8------------------"
		cat ".genesis/manifests/${DEPLOY_ENV}-state.yml"
		echo "----------------->8------------------"
	fi

	genesis info "${DEPLOY_ENV}"

	header "Validating addons..."
	genesis "do" "${DEPLOY_ENV}" -- login
	genesis "do" "${DEPLOY_ENV}" -- credhub-login
	if has_feature "${DEPLOY_ENV}" "vault-credhub-proxy" ; then
		genesis "do" "${DEPLOY_ENV}" -- vault-proxy-login
	fi
	safe target "$safe_target_orig"

	if ! is_proto "$DEPLOY_ENV" ; then
		genesis bosh "${DEPLOY_ENV}" instances --ps
	fi

fi

if [[ "$SKIP_SMOKE_TESTS" == "false" ]]; then
	header "Validating ${DEPLOY_ENV} BOSH director admin / concourse UAA credentials..."
	(
		BOSH_CA_CERT="$(genesis lookup --exodus "$DEPLOY_ENV" ca_cert 2>/dev/null)"
		BOSH_ENVIRONMENT="$(genesis lookup --exodus "$DEPLOY_ENV" url 2>/dev/null)"
		export BOSH_CA_CERT
		export BOSH_ENVIRONMENT

		BOSH_CLIENT="admin" \
		BOSH_CLIENT_SECRET="$(safe read "$vault_path/users/admin:password")" \
		$BOSH env

		BOSH_CLIENT="concourse" \
		BOSH_CLIENT_SECRET="$(safe read "$vault_path/users/concourse:password")" \
		$BOSH env
	)

	# TODO: need an actual smoke-test, but this doesn't exist yet...
	#if ! is_proto "$DEPLOY_ENV" ; then
	#	genesis "do" "${DEPLOY_ENV}" -- smoketests
	#fi
else
	echo "Skipping smoke_tests"
fi

if [[ "$SKIP_CLEAN" == "false" ]]; then
	cleanup "${DEPLOY_ENV}"
else
	echo "Skipping CLEANUP"
fi
