---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ((image/genesis.url))
    tag:        ((image/genesis.tag))

inputs:
- name: git-latest-tag
- name: git-ci

outputs:
- name: work

run:
  path: git-ci/ci/scripts/deploy

params:
  TAG_ROOT:             git-latest-tag
  GENESIS_HONOR_ENV:    1
  GIT_NAME:             Genesis CI Bot
  GIT_EMAIL:            genesis-ci@rubidiumstudios.com
  VAULT_URI:            ((vault.url))
  VAULT_TOKEN:          ((vault.token))
  KIT_SHORTNAME:        bosh
  SECRETS_SEED_DATA:    ((secrets_seed_data))
