---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: starkandwayne/genesis

inputs:
- name: git
- name: git-ci
- name: git-latest-tag

outputs:
- name: spec-check

params:
  GENESIS_HONOR_ENV: 1
  GITHUB_AUTH_TOKEN: ((github.access_token))

run:
  path: git-ci/ci/scripts/spec-check
