---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: registry.ops.scalecf.net/genesis-community/concourse-go
    tag:        latest

inputs:
- name: git
- name: git-ci

run:
  dir: git/spec
  path: ginkgo
  args: [ "-p", "." ]
