---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ((image/genesis.url))
    tag:        ((image/genesis.tag))

inputs:
- name: git
- name: git-ci

run:
  dir: git
  path: prove
  args: [ "-lv", "spec/spec.t", "spec/unit/cloud-config-director-az-map.t", "spec/unit/post-deploy-stemcell.t" ]
