#!/bin/bash
#
# ci/scripts/shipit
#
# Script for generating Github release / tag assets
# and managing release notes for a BOSH Release pipeline
#
# author:  James Hunt <james@niftylogic.com>
# created: 2016-03-30

set -eu

header() {
	echo
	echo "###############################################"
	echo
	echo $*
	echo
}

bail() {
	echo >&2 $* "  Did you misconfigure Concourse?"
	exit 2
}

test -n "${REPO_ROOT:-}"      || bail "REPO_ROOT must be set to the full path to the Git repository."
test -n "${RELEASE_ROOT:-}"   || bail "RELEASE_ROOT must be set to the output directory where release artifacts should go."
test -n "${KIT_SHORTNAME:-}"  || bail "KIT_SHORTNAME must be set to the short name of this kit."
test -n "${GITHUB_OWNER:-}"   || bail "GITHUB_OWNER must be set to the name of the Github user or organization that owns the Git repository."
test -n "${VERSION_FROM:-}"   || bail "VERSION_FROM must be set to the path of the input version file."
test -n "${GIT_EMAIL:-}"      || bail "GIT_EMAIL must be set to an email address to use for Git commits."
test -n "${GIT_NAME:-}"       || bail "GIT_NAME must be set to something; it will be used for Git commits."

test -f "${VERSION_FROM}"     || bail "Version file (${VERSION_FROM}) not found."
VERSION=$(cat ${VERSION_FROM})
test -n "${VERSION}"          || bail "Version file (${VERSION_FROM}) was empty."

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

###############################################################

VERSION=$(cat $VERSION_FROM)
header "Compiling v$VERSION of Genesis Kit..."
pushd $REPO_ROOT
 genesis compile-kit --version "$VERSION" --name "$KIT_SHORTNAME"
popd

header "Assembling Github Release Artifacts..."
mkdir -p ${RELEASE_ROOT}/artifacts
echo "v${VERSION}"      > ${RELEASE_ROOT}/tag
echo "v${VERSION}"      > ${RELEASE_ROOT}/name
mv $REPO_ROOT/*.tar.gz    ${RELEASE_ROOT}/artifacts

cat > ${RELEASE_ROOT}/notification <<EOF
<!here> New ${KIT_SHORTNAME} v${VERSION} released!
EOF

header "Updating Git repository..."
git config --global user.name  "${GIT_NAME}"
git config --global user.email "${GIT_EMAIL}"

pushd git
  # Clean release-notes
  echo -e "\n" > pushme/ci/release_notes.md
  echo -e "## Version: ${VERSION}" > ci/version
  git add -A
  git status
  git commit -m "release v${VERSION}"
popd

header "Merge develop into master"
pushd git-main
  git pull ../git -X theirs --no-edit
popd

cat > ${NOTIFICATION_OUT:-notifications}/message <<EOS
New ${KIT_SHORTNAME} Genesis Kit v${VERSION} released. <https://github.com/${GITHUB_OWNER}/${KIT_SHORTNAME}-genesis-kit/releases/tag/v${VERSION}|Release notes>.
EOS
