---
addons:
- name: toolbelt
  jobs:
  - name: toolbelt
    release: toolbelt
  - name: toolbelt-quick
    release: toolbelt

- name: toolbelt-veritas
  include:
    jobs:
    - name: bbs
      release: diego
    - name: rep
      release: diego
    - name: auctioneer
      release: diego
  jobs:
  - name: toolbelt-veritas
    release: toolbelt

releases:
- name:    "toolbelt"
  version: "3.7.0"

