azs:
- name: z1
  cloud_properties:
    datacenter: ((sl_datacenter))
- name: z2
  cloud_properties:
    datacenter: ((sl_datacenter))
- name: z3
  cloud_properties:
    datacenter: ((sl_datacenter))

vm_types:
- name: default
  cloud_properties:
    cpu:  4
    memory:  8192
    ephemeral_disk_size: 100
    hourly_billing_flag: true
    local_disk_flag: false
    max_network_speed: 100
    hostname_prefix: ((sl_vm_name_prefix))
    domain: ((sl_vm_domain))

disk_types:
- name: default
  disk_size: 100_000
- name: small
  disk_size: 20_000
- name: large
  disk_size: 250_000

networks:
- name: default
  type: manual
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    azs: [z1, z2, z3]
    dns: [((internal_ip)), 8.8.8.8, 10.0.80.11, 10.0.80.12]
    static: ((internal_static_ips))
    reserved: ((internal_reserved_ips))
    cloud_properties:
      vlan_ids:
      - ((sl_vlan_public))
      - ((sl_vlan_private))

- name: dynamic
  type: dynamic
  subnets:
  - dns: [((internal_ip)), 8.8.8.8, 10.0.80.11, 10.0.80.12]
    azs: [z1, z2, z3]
    cloud_properties:
      vlan_ids:
      - ((sl_vlan_public))
      - ((sl_vlan_private))

compilation:
  workers: 5
  reuse_compilation_vms: true
  vm_type: default
  network: dynamic
  az: z1
