#!/usr/bin/env bash

set -e
set -o pipefail

ref=$(cat bosh-deployment/.git/ref | cut -c1-8)

pushd git > /dev/null

if [[ -z $(git config --global user.email) ]]; then
    git config --global user.email "ci@starkandwayne.com"
fi
if [[ -z $(git config --global user.name) ]]; then
    git config --global user.name "CI Bot"
fi

echo "CHECKING git status"
git status

echo "MERGE bosh-deployment repo"
rm -r bosh-deployment
cp -r ../bosh-deployment .
rm -rf bosh-deployment/{ci,tests}

echo "recreate spec-test results to validate: the bosh-deployment update "
pushd spec > /dev/null
# TODO: remove spec/{credhub,vault} if needed? because this will regenerate vault.
rm -rf results/
ginkgo -p
popd

# TODO: figure out how we can maken this less hacky
echo "bumping overlay-releases"
release_name=os-conf
release_version=$( bosh int bosh-deployment/bosh.yml -o bosh-deployment/jumpbox-user.yml --path /releases/name=os-conf/version )
url=$( bosh int bosh-deployment/bosh.yml -o bosh-deployment/jumpbox-user.yml --path /releases/name=os-conf/url )
sha1=$( bosh int bosh-deployment/bosh.yml -o bosh-deployment/jumpbox-user.yml --path /releases/name=os-conf/sha1 )

cat > overlay/releases/os-conf.yml <<YML
- type: replace
  path: /releases?/name=${release_name}?
  value:
    name: ${release_name}
    version: ${release_version}
    url: ${url}
    sha1: ${sha1}
YML

DNS=$(bosh int bosh-deployment/runtime-configs/dns.yml --path /releases)
cat > overlay/releases/bosh-dns.yml <<YML
releases:
${DNS}
YML

echo "commiting to git"
git add bosh-deployment
git add spec/
git commit -m "Update to cloudfoundry/bosh-deployment@$ref"

popd > /dev/null