#!/bin/bash
set -u

action="${1:-''}" ; shift
if [[ "$action" == 'help' ]] ; then
  describe "Target and launch carousel on credhub for this bosh director"
  exit 0
fi

[[ "$action" == 'run' ]] || bail \
  "#R{[ERROR]} Internal error: carousel addon called with invalid argument." \
  "        Expecting help, browse, diff, rotate, or run, got '$1'"

# -- MAIN ----------------------------------------------------------------------
[[ -n "${GENESIS_DEBUG:-}" ]] && set -x

# Check for credhub command
command -v carousel help > /dev/null 2>&1 || bail \
  "#R{[ERROR]} Command 'carousel' not found.  Please install from " \
  "        https://github.com/cloudfoundry-community/carousel"

# Update api target with correct ca's
__exodus="$(exodus --all)"
__bosh_ca_cert="$(echo "$__exodus" | jq -r '.ca_cert')"
__ch_ca_cert="$(echo "$__exodus"   | jq -r '.credhub_ca_cert')"
__ch_pw="$(echo "$__exodus"        | jq -r '.credhub_password')"
__ch_url="$(echo "$__exodus"       | jq -r '.credhub_url')"
__ch_user="$(echo "$__exodus"      | jq -r '.credhub_username')"

unset CREDHUB_SERVER
unset CREDHUB_SECRET
unset CREDHUB_CLIENT
unset CREDHUB_CA_CERT

export BOSH_ENVIRONMENT="$BOSH_URL"
export BOSH_CA_CERT="$(safe read ${GENESIS_SECRETS_BASE}ssl/ca:certificate )"
export BOSH_CLIENT=admin
export BOSH_CLIENT_SECRET="$(safe read ${GENESIS_SECRETS_BASE}users/admin:password )"
export CREDHUB_SERVER="https://$(lookup params.static_ip):8844"
export CREDHUB_CLIENT="credhub-admin"
export CREDHUB_SECRET="$(safe read ${GENESIS_SECRETS_BASE}uaa/clients/credhub_admin:secret )"
export CREDHUB_CA_CERT="$(safe read ${GENESIS_SECRETS_BASE}ssl/ca:certificate; safe read ${GENESIS_SECRETS_BASE}credhub/ca:certificate)"

# Login via stored password
case "$action" in
  (diff)
    command carousel diff 
    ;;
  (rotate)
    command carousel rotate 
    ;;	  
  (*)  # browse
    command carousel browse 
    ;;
esac
