#!/bin/bash
set -u

action="${1:-''}" ; shift
if [[ "$action" == 'help' ]] ; then
  want_feature vault-credhub-proxy || exit 1 # Don't show if not applicable
  describe "Target and log into credhub via vault proxy using safe."
  exit 0
fi

[[ "$action" == 'run' ]] || bail \
  "#R{[ERROR]} Internal error: upload stemcells addon called with invalid argument." \
  "        Expecting help or run, got '$1'"

# -- MAIN ----------------------------------------------------------------------
[[ -n "${GENESIS_DEBUG:-}" ]] && set -x

if ! want_feature vault-credhub-proxy; then
  describe "#R{[ERROR]} Requires feature vault-credhub-proxy"
  exit 1
fi
echo
ip="$(lookup params.static_ip)"
proxy="${GENESIS_ENVIRONMENT}-proxy"
password="$(safe read "${GENESIS_SECRETS_BASE}uaa/clients/credhub_admin:secret")"
export SAFE_TARGET=""
safe target "https://$ip:8200" -k --no-strongbox "$proxy"
echo "credhub-admin:$password" | safe -T "$proxy" auth token
if safe -T "$proxy" set secret/handshake knock=knock >/dev/null 2>&1; then
  if safe -T "$proxy" read secret/handshake >/dev/null 2>&1; then
    describe "" \
             "Successfully connected to Credhub Vault Proxy on #C{https://$ip:8200}" \
             "Target name is #C{$proxy}" \
             ""
    exit 0
  else
    describe "#R{[ERROR]} Could not read from Credhub Vault Proxy on $ip"
  fi
else
  describe "#R{[ERROR]} Authentication failed or could not write to secret/"
fi
exit 1
