#!/bin/bash
set -eu

declare -a merge

validate_features nfs-volume-services small-footprint \
                  local-db local-ha-db mysql-db postgres-db \
                  db-internal-postgres db-external-mysql db-external-postgres \
                  aws-blobstore azure-blobstore gcp-blobstore local-blobstore \
                  blobstore-aws blobstore-azure blobstore-gcp blobstore-webdav \
                  haproxy tls self-signed \
                  shield-dbs shield-blobstore \
                  minimum-vms \
                  haproxy-tls haproxy-notls omit-haproxy

merge=( manifests/cf/base.yml
        manifests/cf/releases.yml
        manifests/cf/certs.yml

        manifests/cf/access.yml
        manifests/cf/bbs.yml
        manifests/cf/cell.yml
        manifests/cf/cloud_controller.yml
        manifests/cf/consul_etcd.yml
        manifests/cf/diego.yml
        manifests/cf/loggregator.yml
        manifests/cf/metron_agent.yml
        manifests/cf/nats.yml
        manifests/cf/router.yml
        manifests/cf/uaa.yml

        manifests/cf/smoke-tests.yml)

case "$(bosh_cpi)" in
(azure*) merge+=( manifests/azure.yml ) ;;
esac

for want in shield-dbs shield-blobstore; do
  if want_feature $want; then
    echo >&2 "The '$want' feature has been deprecated, in favor of BOSH add-ons"
  fi
done
if want_feature omit-haproxy; then
  echo >&2 "You no longer need to explicitly specify the 'omit-haproxy' feature."
  echo >&2 "If you remove it, everything will still work as expected."
fi



  ########  ##        #######  ########   ######  ########  #######  ########  ########
  ##     ## ##       ##     ## ##     ## ##    ##    ##    ##     ## ##     ## ##
  ##     ## ##       ##     ## ##     ## ##          ##    ##     ## ##     ## ##
  ########  ##       ##     ## ########   ######     ##    ##     ## ########  ######
  ##     ## ##       ##     ## ##     ##       ##    ##    ##     ## ##   ##   ##
  ##     ## ##       ##     ## ##     ## ##    ##    ##    ##     ## ##    ##  ##
  ########  ########  #######  ########   ######     ##     #######  ##     ## ########

blobstore=0
for want in ${GENESIS_REQUESTED_FEATURES}; do
  case "$want" in
  # Blobstore selector feature flags
  aws-blobstore|azure-blobstore|gcp-blobstore|local-blobstore)
    blobstore=$(( blobstore + 1 ))
    merge+=( manifests/blobstore/${want%-blobstore}.yml )
    ;;

  blobstore-webdav)
    blobstore=$(( blobstore + 1 ))
    echo >&2 "The $want feature has been renamed to local-blobstore"
    merge+=( manifests/blobstore/local.yml )
    ;;

  blobstore-aws|blobstore-azure|blobstore-gcp)
    blobstore=$(( blobstore + 1 ))
    echo >&2 "The $want feature has been renamed to ${want#blobstore-}-blobstore"
    merge+=( manifests/blobstore/${want#blobstore-}.yml )
    ;;
  esac
done
# If we haven't chosen a blobstore, use local
if [[ $blobstore == 0 ]]; then
  merge+=( manifests/blobstore/local.yml )
fi



  ########     ###    ########    ###    ########     ###     ######  ########
  ##     ##   ## ##      ##      ## ##   ##     ##   ## ##   ##    ## ##
  ##     ##  ##   ##     ##     ##   ##  ##     ##  ##   ##  ##       ##
  ##     ## ##     ##    ##    ##     ## ########  ##     ##  ######  ######
  ##     ## #########    ##    ######### ##     ## #########       ## ##
  ##     ## ##     ##    ##    ##     ## ##     ## ##     ## ##    ## ##
  ########  ##     ##    ##    ##     ## ########  ##     ##  ######  ########

database=0
for want in ${GENESIS_REQUESTED_FEATURES}; do
  case "$want" in
  # Database selector feature flags
  mysql-db|postgres-db)
    database=$(( database + 1 ))
    merge+=( manifests/db/${want%-db}.yml )
    ;;

  local-db)
    database=$(( database + 1 ))
    merge+=( manifests/db/local.yml )
    merge+=( manifests/db/local-single.yml )
    ;;

  local-ha-db)
    database=$(( database + 1 ))
    merge+=( manifests/db/local.yml )
    merge+=( manifests/db/local-ha.yml )
    ;;

  db-internal-postgres)
    database=$(( database + 1 ))
    echo >&2 "The db-internal-postgres flag has been renamed to 'local-db'"
    merge+=( manifests/db/local.yml )
    ;;

  db-external-*)
    database=$(( database + 1 ))
    echo >&2 "The $want flag has been renamed to '${want#db-external-}-db'"
    merge+=( manifests/db/${want#db-external-}.yml )
    ;;
  esac
done
# If we haven't chosen a database, use local
if [[ $database == 0 ]]; then
  merge+=( manifests/db/local.yml )
fi



     ###    ########  ########   #######  ##    ##  ######
    ## ##   ##     ## ##     ## ##     ## ###   ## ##    ##
   ##   ##  ##     ## ##     ## ##     ## ####  ## ##
  ##     ## ##     ## ##     ## ##     ## ## ## ##  ######
  ######### ##     ## ##     ## ##     ## ##  ####       ##
  ##     ## ##     ## ##     ## ##     ## ##   ### ##    ##
  ##     ## ########  ########   #######  ##    ##  ######

for want in ${GENESIS_REQUESTED_FEATURES}; do
  case "$want" in
  azure|nfs-volume-services|small-footprint)
    merge+=( manifests/addons/$want.yml )
    ;;

  minimum-vms)
    echo >&2 "The 'minimum-vms' feature flag has been renamed to 'small-footprint'"
    merge+=( manifests/addons/small-footprint.yml )
    ;;
  esac
done



  ##     ##    ###    ########  ########   #######  ##     ## ##    ##
  ##     ##   ## ##   ##     ## ##     ## ##     ##  ##   ##   ##  ##
  ##     ##  ##   ##  ##     ## ##     ## ##     ##   ## ##     ####
  ######### ##     ## ########  ########  ##     ##    ###       ##
  ##     ## ######### ##        ##   ##   ##     ##   ## ##      ##
  ##     ## ##     ## ##        ##    ##  ##     ##  ##   ##     ##
  ##     ## ##     ## ##        ##     ##  #######  ##     ##    ##

if want_feature haproxy; then
  merge+=( manifests/routing/haproxy.yml )
  if want_feature tls; then
    merge+=( manifests/routing/haproxy-tls.yml )
  fi

elif want_feature haproxy-tls; then
  echo >&2 "The haproxy-tls feature flag has been deprecated."
  echo >&2 "Please replace it with the 'haproxy' and 'tls' flags."

  merge+=( manifests/routing/haproxy.yml
           manifests/routing/haproxy-tls.yml )

elif want_feature haproxy-notls; then
  echo >&2 "The haproxy-notls feature flag has been deprecated."
  echo >&2 "Please replace it with the 'haproxy' feature flag."
  echo >&2 "You are HIGHLY ENCOURAGED to also add the 'tls' flag."

  merge+=( manifests/routing/haproxy.yml )
fi



   ######     ###    ##    ## #### ######## ##    ##
  ##    ##   ## ##   ###   ##  ##     ##     ##  ##
  ##        ##   ##  ####  ##  ##     ##      ####
   ######  ##     ## ## ## ##  ##     ##       ##
        ## ######### ##  ####  ##     ##       ##
  ##    ## ##     ## ##   ###  ##     ##       ##
   ######  ##     ## ##    ## ####    ##       ##

# Sanity Check Time
# If we have chosen more than one Blobstore, that's a problem.
if [[ $blobstore > 1 ]]; then
  echo >&2 "You have enabled more than one Blobstore feature flag."
  exit 1
fi
# If we have chosen more than one Database, that's a problem.
if [[ $database > 1 ]]; then
  echo >&2 "You have enabled more than one Database feature flag."
  exit 1
fi

echo "${merge[@]}"
