#!/bin/bash
set -eu

declare -a merge

validate_features aws azure google openstack vsphere warden \
                  aws-cpi azure-cpi google-cpi openstack-cpi vsphere-cpi warden-cpi \
                  aws-init azure-init google-init openstack-init vsphere-init bosh-init \
                  proxy credhub shield bosh proto skip-op-users registry vault-credhub-proxy \
                  external-db external-db-ca external-db-no-tls s3-blobstore \
                  iam-instance-profile s3-blobstore-iam-instance-profile \
                  external-db-mysql external-db-postgres blacksmith-integration \
                  node-exporter

#
# We always start out with the skeleton of a BOSH deployment,
# and add-in a local UAA and a Credhub
# merge=( manifests/versions.yml
#         manifests/bosh/bosh.yml
#         manifests/bosh/uaa.yml
#         manifests/bosh/credhub.yml )

merge=( bosh-deployment/bosh.yml
        bosh-deployment/uaa.yml
        bosh-deployment/credhub.yml )

iaas=0
extdb=

for want in ${GENESIS_REQUESTED_FEATURES}; do
  case "$want" in


  # IaaS selector feature flags
  aws|aws-cpi|azure|azure-cpi|google|google-cpi|openstack|openstack-cpi|vsphere|vpshere-cpi|warden|warden-cpi)
    if [[ $want =~ .*-cpi ]]; then
      want=${want%-cpi}
      describe >&2 "" \
        "The #c{${want}-cpi} feature is now deprecated. You should use #c{${want}} instead."
    fi

    iaas=$(( iaas + 1 ))

    if [[ $want == "warden" ]]; then
      # when using warden we want the bosh-lite.yml to be merged
      # this will add and configure the garden deamon
      merge+=( bosh-deployment/bosh-lite.yml
              "overlay/cpis/${want}.yml" )
    else
      merge+=( "bosh-deployment/${want}/cpi.yml"
             "overlay/cpis/${want}.yml" )
    fi

    if want_feature "registry"; then
      #  Azure, AWS, Google, and Openstack do not need a registry anymore,
      #  but you may still need it if you have deployments with stemcells
      #  that are too old to take advantage of this.
      #  Additionally, vSphere and Warden don't need a registry in any cases.
      merge+=( "manifests/addons/registry.yml" )
    fi

    if want_feature proto; then
      if [[ $want == "warden" ]]; then
        # It doesn't make sense to deploy a proto-BOSH to Warden,
        # since Warden is the only IaaS that doesn't exist in its
        # own right, apart from BOSH.  There is now "Warden" cloud...
        #
        printf >&2 "BOSH Warden CPI can not be deployed as a proto-BOSH"
        exit 2
      fi
    else
      merge+=( overlay/no-proto.yml )
    fi

    if want_feature "${want}-init"; then
      bail "" \
        "The #c{${want}-init} feature no longer does anything. You need to use the #c{proto} feature" \
        "instead, regardless of which CPI you're targeting"
    fi

    if want_feature "iam-instance-profile"; then
      [[ "$want" == "aws" ]] || bail "" "Cannot use IAM instance profiles if not deploying to AWS"
      merge+=( "manifests/addons/iam-profile.yml" )
    fi

    if want_feature "s3-blobstore"; then
      merge+=( "manifests/addons/s3-blobstore.yml" )
      if want_feature "s3-blobstore-iam-instance-profile"; then
        [[ "$want" == "aws" ]] || bail "" "Cannot use IAM instance profiles if not deploying to AWS"
        merge+=( "manifests/addons/s3-blobstore-iam-profile.yml" )
      fi
    fi

    if want_feature "proto" ; then
      # If this is a proto-BOSH and one of the iam-instance-profile or
      # s3-blobstore-iam-instance-profile features are requested, then we need
      # to ensure the proto-BOSH has the correct cloud properties
      if want_feature "iam-instance-profile" || want_feature "s3-blobstore-iam-instance-profile"; then
        merge+=( "manifests/addons/proto-iam-profile.yml" )
      fi
    fi
    ;;

  external-db|external-db-mysql|external-db-postgres)
    [[ -z "$extdb" ]] || bail "" "Cannot specify both $want and $extdb - pick one"
    extdb="$want"
    merge+=( \
      "manifests/addons/external-db-internal-db-cleanup.yml" \
      "manifests/addons/external-db.yml" \
    )
    [[ "$want" == "external-db-mysql" ]] && merge+=( "manifests/addons/external-db-mysql.yml" )

    if want_feature "external-db-no-tls" ; then
      merge+=( "manifests/addons/external-db-no-tls.yml" )
    else
      merge+=( "manifests/addons/external-db-ca.yml" )
    fi
    ;;

  # addons
  vault-credhub-proxy|blacksmith-integration|node-exporter)
    merge+=( "manifests/addons/$want.yml" )
    ;;

  # Deprecated (now-noop) feature flags
  shield)
    describe >&2 "" \
      "The #c{shield} feature is no longer supported.  Instead, please add the" \
      "shield agent to your runtime configuration."
    ;;

  external-db-ca)
    describe >&2 "" \
      "The functionality contained within the 'external-db-ca' has become mandatory" \
      "and has therefore been merged into the base kits #c{external-db-postgres} and" \
      "#c{external-db-mysql}. You can remove the 'external-db-ca' feature without any changes" \
      "occurring."
    ;;

  proxy|credhub)
    describe >&2 "" \
      "You no longer need to explicitly specify the #c{$want} feature." \
      "If you remove it, everything will still work as expected."
    ;;

  esac
done

if ! want_feature skip-op-users; then
  # jumpbox is only used for os-conf release
  merge+=( bosh-deployment/jumpbox-user.yml 
          overlay/addons/op-users.yml 
         )
fi

# Sanity Check Time!
# If we haven't chosen an IaaS, that's a problem.
[[ $iaas == 0 ]] && bail "" "You have not enabled an IaaS feature flag."

# If we have chosen more than one IaaS, that's a problem.
[[ $iaas -gt 1 ]] && bail "" "You have enabled more than one IaaS feature flag."

if want_feature proto; then
  merge+=( overlay/base-proto.yml )
fi

merge+=( overlay/base.yml )


echo "${merge[@]}"
