#!/bin/bash
set -eu
vault="secret/$GENESIS_VAULT_PREFIX"

base=$(lookup params.base_domain)
system_domain=$(lookup params.system_domain system.$base)

api_url=https://api.$system_domain
password=$(safe read $vault/admin_user:password)

      echo "cloud foundry api"
  describe "       url: #C{$api_url}"
  describe "  username: #M{admin}"
  describe "  password: #G{$password}"

      echo
      curl -m5 -Lsk $api_url/v2/info | jq -Cr . | sed -e 's/^/  /'
