---
params:
  azure_environment:    AzureCloud
  azure_resource_group: (( param "Specify the resource group for Azure" ))
  azure_default_sg:     (( param "Specify the default security group for your Azure VMs" ))

instance_groups:
  - name: bosh
    jobs:
      - name: azure_cpi
        release: bosh-azure-cpi
        properties:
          azure:
            environment: (( grab params.azure_environment ))
            subscription_id: (( vault meta.vault "/azure:subscription_id" ))
            tenant_id: (( vault meta.vault "/azure:tenant_id" ))
            client_id: (( vault meta.vault "/azure:client_id" ))
            client_secret: (( vault meta.vault "/azure:client_secret" ))
            resource_group_name: (( grab params.azure_resource_group ))
            default_security_group: (( grab params.azure_default_sg ))
            ssh_user: vcap
            ssh_public_key: (( vault meta.vault "/azure/ssh:public" ))
            use_managed_disks: true
          blobstore: (( grab instance_groups.bosh.jobs.blobstore.properties.blobstore ))
          env: (( grab instance_groups.bosh.jobs.director.properties.env ))
          nats: (( grab instance_groups.bosh.jobs.nats.properties.nats ))
          agent:
            mbus: (( grab instance_groups.bosh.jobs.director.properties.agent.mbus ))
          registry: (( grab instance_groups.bosh.jobs.registry.properties.registry ))
          ntp: (( grab instance_groups.bosh.jobs.director.properties.ntp ))

      - name: director
        properties:
          director:
            cpi_job: azure_cpi

releases:
  - name: bosh-azure-cpi
    .:    (( inject meta.releases.bosh-azure-cpi ))
