---
instance_groups:
  - name: blobstore
    jobs:
      - name:    shield-agent
        release: shield
    properties:
      shield-url: (( grab params.shield_core_url ))
      agent:
        key: (( vault params.shield_key_vault_path ))
      core:
        ca: (( vault params.shield_ca_vault_path ))
      env:
        http_proxy:  (( grab params.http_proxy  || "" ))
        https_proxy: (( grab params.https_proxy || "" ))
        no_proxy:    (( grab params.no_proxy    || meta.default.proxy ))
