---
meta:
  ocfp:
      iam:
        ec2: # For BOSH to boot VMs
          access_key:  (( vault meta.ocfp.vault.config "/bosh/iam/bosh:access_key" ))
          secret_key:  (( vault meta.ocfp.vault.config "/bosh/iam/bosh:secret_key" ))
