---
meta:
  ocfp:
    env:
      az:     (( grab params.availability_zones[0] || "z1" ))
      subnet: (( grab params.ocfp_subnet || "ocfp-0" ))

    vault:
      config_slug:   (( grab params.ocfp_vault_config_slug || genesis.ocfp_env ))
      config:        (( concat genesis.ocfp_config_mount meta.ocfp.vault.config_slug ))

    certs:
      trusted:
        - (( append ))
        # TODO: Just safe set empty ca for now???
        - (( vault genesis.secrets_mount "certs/org:ca" )) # Organization CA, if exists
        - (( vault genesis.secrets_mount "certs/dbs:ca" )) # External Databases CA

    bosh:
      ip:        (( vault meta.ocfp.vault.config "/vpc/subnets/" meta.ocfp.env.subnet "/reserved-ips:bosh_ip" )) # Shouldn't this just be ocfp-0:ip ???  instead of /bosh/net/bosh:ip
      gateway:   (( vault meta.ocfp.vault.config "/vpc/subnets/" meta.ocfp.env.subnet ":gateway" )) # Shouldn't this just be ocfp-0:gateway ??? instead of /bosh/net/bosh:gateway
      cidr:      (( vault meta.ocfp.vault.config "/vpc/subnets/" meta.ocfp.env.subnet ":cidr_block" ))
      subnet_id: (( vault meta.ocfp.vault.config "/vpc/subnets/" meta.ocfp.env.subnet ":id" ))
      region:    (( vault meta.ocfp.vault.config "/vpc:region" ))

      dns:
        - (( vault meta.ocfp.vault.config "/vpc:dns" ))

      # TODO: Didn't do keys yet...
      key_name:    (( vault meta.ocfp.vault.config "/bosh/keys/bosh:name" ))
      private_key: (( vault meta.ocfp.vault.config "/bosh/keys/bosh:private" ))

      s3:
        bucket_name: (( vault meta.ocfp.vault.config "/bosh/blobstores/bosh:name" ))
        region:      (( vault meta.ocfp.vault.config "/bosh/blobstores/bosh:region" ))

      iam:
        s3: # For Blobstore
          # TODO: fetch from blobstore definition as above???
          access_key:  (( vault meta.ocfp.vault.config "/bosh/iam/s3:access_key" ))
          secret_key:  (( vault meta.ocfp.vault.config "/bosh/iam/s3:secret_key" ))

      disk_size:       (( grab params.disk_size || 65536 ))
      disk_encryption: true # Default to encrypted at rest
