---
meta:
  ocfp:
    env:
      scale: (( grab params.env.scale || "dev" ))

    vault:
      tf: (( concat genesis.secrets_mount "tf/" genesis.vault_env ))

    certs:
      trusted:
        - (( vault genesis.secrets_mount "certs/org:ca" )) # Organization CA, if exists
        - (( vault genesis.secrets_mount "certs/dbs:ca" )) # External Databases CA

    bosh:
      ip:        (( vault meta.ocfp.vault.tf "/net/bosh:ip" ))
      gateway:   (( vault meta.ocfp.vault.tf "/net/bosh:gateway" ))
      cidr:      (( vault meta.ocfp.vault.tf "/iaas/subnets/ocfp/0:cidr_block" )) 
      subnet_id: (( vault meta.ocfp.vault.tf "/iaas/subnets/ocfp/0:id" ))
      region:    (( vault meta.ocfp.vault.tf "/iaas/region:name" ))

      dns:
        - (( vault meta.ocfp.vault.tf "/iaas/vpc:dns" ))

      mgmt:
        # For mgmt (create-env) it's the subnet 0's AZ
        az: (( vault meta.ocfp.vault.tf "/iaas/subnets/ocfp/0:availability_zone" ))

        sgs:
          - (( vault meta.ocfp.vault.tf "/iaas/sgs/default:id" ))
          - (( vault meta.ocfp.vault.tf "/iaas/sgs/mgmt:id" ))

      ocf:
        sgs:
          - (( vault meta.ocfp.vault.tf "/iaas/sgs/default:id" ))
          - (( vault meta.ocfp.vault.tf "/iaas/sgs/ocf:id" ))

      key_name:    (( vault meta.ocfp.vault.tf "/keys/bosh:keypair_name" ))
      private_key: (( vault meta.ocfp.vault.tf "/keys/bosh:private" ))

      s3:
        bucket_name: (( vault meta.ocfp.vault.tf "/blobstores/bosh:name" ))
        region:      (( vault meta.ocfp.vault.tf "/blobstores/bosh:region" ))

      iam:
        ec2:
          access_key:  (( vault meta.ocfp.vault.tf "/iam/bosh:access_key" ))
          secret_key:  (( vault meta.ocfp.vault.tf "/iam/bosh:secret_key" ))
        s3:
          access_key:  (( vault meta.ocfp.vault.tf "/iam/s3:access_key" ))
          secret_key:  (( vault meta.ocfp.vault.tf "/iam/s3:secret_key" ))

      disk_size:            (( grab params.disk_size || "64536" ))
      disk_encryption:      true # Default to encrypted at rest

      mbus: # TODO: Bosh >274 mbus will change
        password: (( vault meta.vault "/mbus_bootstrap:password" ))
        ssl:
          ca:   (( vault meta.vault "/ssl/ca:certificate" ))
          cert: (( vault meta.vault "/ssl/mbus:certificate" ))
          key:  (( vault meta.vault "/ssl/mbus:key" ))
  
  dbs:
    bosh:
      adapter:  (( vault meta.vault "/db/bosh:scheme"   ))
      user:     (( vault meta.vault "/db/bosh:username" ))
      password: (( vault meta.vault "/db/bosh:password" ))
      host:     (( vault meta.vault "/db/bosh:hostname" ))
      port:     (( vault meta.vault "/db/bosh:port"     ))
      database: (( vault meta.vault "/db/bosh:database" ))
      tls:
        enabled: true
        cert:
          ca:   (( vault meta.vault "/db/bosh:ca" ))

    credhub:
      type:     (( vault meta.vault "/db/credhub:scheme"   ))
      username: (( vault meta.vault "/db/credhub:username" ))
      password: (( vault meta.vault "/db/credhub:password" ))
      host:     (( vault meta.vault "/db/credhub:hostname" ))
      port:     (( vault meta.vault "/db/credhub:port"     ))
      database: (( vault meta.vault "/db/credhub:database" ))
      require_tls: true
      tls_ca:   (( vault meta.vault "/db/credhub:ca" ))

    uaa:
      type:     (( vault meta.vault "/db/uaa:scheme"   ))
      username: (( vault meta.vault "/db/uaa:username" ))
      password: (( vault meta.vault "/db/uaa:password" ))
      hostname: (( vault meta.vault "/db/uaa:hostname" ))
      port:     (( vault meta.vault "/db/uaa:port"     ))
      database: (( vault meta.vault "/db/uaa:database" ))
      tls:      enabled
      ca:       (( vault meta.vault "/db/uaa:ca" ))

  releases: # NOTE: This is because of runtime config
    toolbelt:
      version: "3.7.0"
      sha1: "377b390b7f5d358a2dae463109350250a769eb3f"
      url: (( concat "https://bosh.io/d/github.com/cloudfoundry-community/toolbelt-boshrelease?v=" meta.releases.toolbelt.version ))

