---
meta:
  ocfp:
    env:
      scale: (( grab params.env.scale || "dev" ))

    vault:
      tf: (( concat genesis.secrets_mount "tf/" genesis.vault_env ))

    certs:
      trusted:
        - (( vault genesis.secrets_mount "/certs/org:ca" )) # Organization CA, if exists
        - (( vault genesis.secrets_mount "/certs/dbs:ca" )) # External Databases CA

  releases: # NOTE: This is because of runtime config
    toolbelt:
      version: "3.7.0"
      sha1: "377b390b7f5d358a2dae463109350250a769eb3f"
      url: (( concat "https://bosh.io/d/github.com/cloudfoundry-community/toolbelt-boshrelease?v=" meta.releases.toolbelt.version ))

