---
meta:
  ocfp:
    env:
      az:     (( grab params.availability_zones[0] || "z1" ))
      subnet: (( grab params.ocfp_subnet || "ocfp-0" ))

    vault:
      config_slug:   (( grab params.ocfp_vault_config_slug || genesis.ocfp_env ))
      config:        (( concat genesis.ocfp_config_mount meta.ocfp.vault.config_slug ))

    # certs/org.ca and the blacksmith ca in blacksmith exodus will be added automagically
    # if they exist in the vault, and certs/dbs:ca will be added if external dbs are used
    certs:
      trusted: []

    bosh:
      ip:        (( vault meta.ocfp.vault.config "/net/subnets/" meta.ocfp.env.subnet "/reserved-ips:bosh_ip" )) # Shouldn't this just be ocfp-0:ip ???  instead of /bosh/net/bosh:ip
      gateway:   (( vault meta.ocfp.vault.config "/net/subnets/" meta.ocfp.env.subnet ":gateway" )) # Shouldn't this just be ocfp-0:gateway ??? instead of /bosh/net/bosh:gateway
      cidr:      (( vault meta.ocfp.vault.config "/net/subnets/" meta.ocfp.env.subnet ":cidr_block" ))
      subnet_id: (( vault meta.ocfp.vault.config "/net/subnets/" meta.ocfp.env.subnet ":id" ))
      region:    (( vault meta.ocfp.vault.config "/net:region" ))

      dns:
        - (( vault meta.ocfp.vault.config "/net:dns" ))

      s3:
        bucket_name: (( vault meta.ocfp.vault.config "/bosh/blobstores/bosh:name" ))
        region:      (( vault meta.ocfp.vault.config "/bosh/blobstores/bosh:region" ))

      disk_size_in_mb: (( grab params.persistant_disk_size_in_mb ))
      disk_encryption: true # Default to encrypted at rest
