---
meta:
  env_name:          (( grab $GENESIS_ENVIRONMENT ))
  env_slug:          (( grab $GENESIS_SECRETS_SLUG ))
  env_scale:         (( grab params.env.scale || "dev" ))
  #vault: set by genesis functionality, same value as vault_env_path below
  vault_mount:       (( grab $GENESIS_SECRETS_MOUNT ))
  vault_exodus_path: (( grab $GENESIS_EXODUS_MOUNT ))
  vault_tf_path:     (( concat meta.vault_mount "tf/" meta.env.slug ))
  vault_env_path:    (( concat meta.vault_mount meta.env.slug ))
  vault_certs_path:  (( concat meta.vault_mount "certs" ))

  trusted_certs:
    - (( vault meta.vault_certs_path "/org:ca" )) # Organization CA, if exists
    - (( vault meta.vault_certs_path "/dbs:ca" )) # External Databases CA

  releases: # NOTE: This is because of runtime config
    toolbelt:
      version: "3.7.0"
      sha1: "377b390b7f5d358a2dae463109350250a769eb3f"
      url: (( concat "https://bosh.io/d/github.com/cloudfoundry-community/toolbelt-boshrelease?v=" meta.releases.toolbelt.version ))

