#!/bin/bash

set -e

pushd git
results_file="../spec-check/diff-$(date -u +%Y%m%d%H%M%S)"

# Run as a script to preserve color output
script --flush --quiet \
  --return  "$results_file" \
  --command '../git-ci/ci/tasks/spec-check/spec-check "$(cat ../git-latest-tag/.git/ref)"'

# Trim script header/footer (ignore error)
sed -i '1d;$d' "$results_file" || true
