#!/bin/bash
set -eu

header() {
	echo
	echo "###############################################"
	echo
	echo $*
	echo
}

cleanup() {
	for deployment in "$@"; do
		echo "> deleting ${deployment}"
		$BOSH -n -d "${deployment}" delete-deployment
	done
}

header "Validating BOSH_* environment variables..."
set | grep BOSH_ || true

header "Checking previous deployments on ${BOSH_ENVIRONMENT}..."
$BOSH deployments

header "Cleaning up from any previous deployments (if necessary)..."
cleanup ci-baseline-bosh
safe rm -rf secret/genesis-ci/bosh
safe cp -rf secret/genesis-ci/static/bosh secret/genesis-ci/bosh/ci/baseline

header "Deploying BASELINE environment to verify functionality..."
genesis secrets --vault da-vault add ci-baseline
genesis deploy -n ci-baseline
$BOSH -d ci-baseline-bosh instances --ps
header "Validating BASELINE BOSH director admin / concourse UAA credentials..."
(BOSH_CA_CERT=$(safe read secret/genesis-ci/bosh/ci/baseline/ssl/ca:certificate)
 BOSH_ENVIRONMENT=https://10.200.138.1:25555

 BOSH_CLIENT=admin
 BOSH_CLIENT_SECRET=$(safe read secret/genesis-ci/bosh/ci/baseline/users/admin:password)
 $BOSH env

 BOSH_CLIENT=concourse
 BOSH_CLIENT_SECRET=$(safe read secret/genesis-ci/bosh/ci/baseline/users/concourse:password)
 $BOSH env)
cleanup ci-baseline-bosh
