---
instance_groups:
  - name: bosh
    properties:
      director: 
        db:
          host: (( grab params.external_db_host ))
          port: (( grab params.external_db_port ))
          user: bosh_user
          password: (( vault meta.vault "/external-db/bosh_user:password" ))
          adapter: (( grab params.external_db_adapter || "postgres" ))
          database: bosh
          tls:
            enabled: true

    jobs:
      - name: credhub
        properties:
          credhub:
            data_storage:
              host: (( grab params.external_db_host ))
              port: (( grab params.external_db_port ))
              database: credhub
              username: credhub_user
              password: (( vault meta.vault "/external-db/credhub_user:password" ))
              require_tls: true
              type: (( grab params.external_db_adapter || "postgres" ))

      - name: uaa
        properties:
          uaadb:
            address: (( grab params.external_db_host ))
            port: (( grab params.external_db_port ))
            tls: enabled
            databases:
              - name: uaa
                tag: uaa
            roles:
              - name: uaa_user
                password: (( vault meta.vault "/external-db/uaa_user:password" ))
                tag: admin
            db_scheme: (( grab params.external_db_adapter || "postgres" ))
