---
meta:
  vault: (( concat "secret/" params.vault ))

  vcap_password: (( vault meta.vault "/vcap:password-crypt-sha512" ))

  bosh:
    blobstore:
      agent:
        user: blobstore-user
        pass: (( vault meta.vault "/blobstore/agent:password" ))
      director:
        user: director-user
        pass: (( vault meta.vault "/blobstore/director:password" ))
    db:
      user: boshdb
      pass: (( vault meta.vault "/db:password" ))
    nats:
      user: natsuser
      pass: (( vault meta.vault "/nats:password" ))

    registry:
      user: registry-user
      pass: (( vault meta.vault "/registry:password" ))
