---
variables: ~

resource_pools: ~
networks: ~
disk_pools: ~

name: (( grab params.name ))

instance_groups:
- name: bosh
  azs: (( grab params.availability_zones ))
  stemcell: default
  networks:
  - (( replace ))
  - name: (( grab params.bosh_network ))
    static_ips: [(( grab params.static_ip ))]
  vm_type: (( grab params.bosh_vm_type ))

meta:
  vault: (( concat "secret/" params.vault ))

  vcap_password: (( vault meta.vault "/vcap:password-crypt-sha512" ))

  bosh:
    blobstore:
      agent:
        user: blobstore-user
        pass: (( vault meta.vault "/blobstore/agent:password" ))
      director:
        user: director-user
        pass: (( vault meta.vault "/blobstore/director:password" ))
    users:
    - name: hm
      username: resurrector
      password: (( vault meta.vault "/users/hm:password" ))
    - name: admin
      username: admin
      password: (( vault meta.vault "/users/admin:password" ))
    db:
      user: boshdb
      pass: (( vault meta.vault "/db:password" ))
    nats:
      user: natsuser
      pass: (( vault meta.vault "/nats:password" ))

    registry:
      user: registry-user
      pass: (( vault meta.vault "/registry:password" ))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-120000
  update_watch_time: 30000-120000
  serial: true

stemcells:
- alias: default
  os: (( grab params.stemcell_os ))
  version: (( grab params.stemcell_version ))
