jobs:
- name: bosh-upstream
  public: true
  serial: true
  plan:
  - do:
    - in_parallel:
      - { get: git, trigger: false, passed: [spec-tests] }
      - { get: git-ci, trigger: false}
      - { get: bosh-deployment, trigger: true }
    - task: bosh-deployment
      file: git-ci/ci/tasks/get-latest-bosh-deployment.yml
      params:
        GIT_EMAIL:        (( grab meta.git.email ))
        GIT_NAME:         (( grab meta.git.name ))
    - put: git
      params:
        merge: true
        repository: git
    on_success:
      put: notify
      params:
        topic:   (( concat meta.shout.topic "-$BUILD_JOB_NAME" ))
        message: tests job '$BUILD_JOB_NAME' succeeded.
        ok:      yes
        link:    (( grab meta.shout.links.build ))
    on_failure:
      put: notify
      params:
        topic:   (( concat meta.shout.topic "-$BUILD_JOB_NAME" ))
        message: tests job '$BUILD_JOB_NAME' failed.
        ok:      no
        link:    (( grab meta.shout.links.build ))
