jobs:
- name: deploy-proto
  public: true
  serial_groups: [testing-proto]
  plan:
  - do:
    - in_parallel:
      - { get: version,    passed: [spec-check, spec-tests]}
      - { get: build,      passed: [spec-check, spec-tests], trigger: true }
      - { get: spec-check, passed: [spec-check]}
      - { get: git,        passed: [spec-check, spec-tests]}
      - { get: git-ci }
    - task: test-deploy-proto
      file: git-ci/ci/tasks/deploy.yml
      params:
        .: (( inject meta.task_connectivity_params ))
        DEPLOY_ENV:           (( concat "ci-" meta.iaas "-proto" ))
        KIT_SHORTNAME:        (( grab meta.kit ))
        SKIP_FRESH:           false
        SKIP_REPLACE_SECRETS: false
        SKIP_SMOKE_TESTS:     false
        SKIP_CLEAN:           false
    on_failure:
      put: notify
      params:
        topic:   (( concat meta.shout.topic "-$BUILD_JOB_NAME" ))
        message: tests job '$BUILD_JOB_NAME' failed.
        ok:      no
        link:    (( grab meta.shout.links.build ))
