jobs:
- name: prepare
  public: true
  serial: true
  plan:
  - do:
    - in_parallel:
      - { get: version,    passed: (( grab meta.blocking_tests )), params: {bump: final} }
      - { get: spec-check, passed: (( grab meta.blocking_tests )) }
      - { get: git,        passed: (( grab meta.blocking_tests )), trigger: true }
      - { get: git-ci }
      - { get: git-latest-tag }
      - { get: release-notes }
    - task: generate-release-notes
      file: git-ci/ci/tasks/generate-release-notes.yml
      params:
        RELEASE_NOTES_WEB_URL:  (( grab meta.github.release_notes.edit ))
        RELEASE_NOTES_FILE:     (( grab meta.github.release_notes.file ))
        GIT_NAME:               (( grab meta.git.name ))
        GIT_EMAIL:              (( grab meta.git.email ))
        VAULT_URI:              (( grab meta.vault.url ))
        VAULT_TOKEN:            (( grab meta.vault.token ))
        KIT_SHORTNAME:          (( grab meta.kit ))
    - put: release-notes
      params:
        rebase: true
        repository: release-notes
    on_failure:
      put: notify
      params:
        topic:   (( concat meta.shout.topic "-$BUILD_JOB_NAME" ))
        message: release candidate job 'pre' failed (which is unusual).
        ok:      no
        link:    (( grab meta.shout.links.build ))
