jobs:
- name: ship-prerelease
  public: true
  serial: false
  plan:
  - do:
    - in_parallel:
      - { get: build,   passed: [build-kit]}
      - { get: version, passed: [build-kit]}
      - { get: git,     passed: [build-kit]}
      - { get: git-ci }
      - { get: git-latest-tag }
    - task: ship-prerelease
      file: git-ci/ci/tasks/ship-prerelease.yml
      params:
        REPO_ROOT:    git
        VERSION_FROM: version/number
        RELEASE_ROOT: gh
        NOTIFICATION_OUT: notifications
        GITHUB_OWNER:  (( grab meta.github.owner ))
        GIT_EMAIL:     (( grab meta.git.email ))
        GIT_NAME:      (( grab meta.git.name ))
        KIT_SHORTNAME: (( grab meta.kit ))
    - put: git
      params:
        merge: true
        repository: git
    - put: github-prerelease
      params:
        name:   gh/name
        tag:    gh/tag
        body:   release-notes/notes.md
        globs: [gh/artifacts/*]
    on_failure:
      put: notify
      params:
        topic:   (( concat meta.shout.topic "-$BUILD_JOB_NAME" ))
        message: tests job '$BUILD_JOB_NAME' failed.
        ok:      no
        link:    (( grab meta.shout.links.build ))
