jobs:
- name: upgrade-non-proto
  public: true
  serial: true
  serial_groups: [test-non-proto2]
  plan:
  - do:
    - in_parallel:
      - { get: version,    passed: [spec-check, spec-tests]}
      - { get: build,      passed: [spec-check, spec-tests], trigger: true }
      - { get: spec-check, passed: [spec-check]}
      - { get: git,        passed: [spec-check, spec-tests]}
      - { get: git-ci }
      - { get: git-latest-tag }
    - task: deploy-stable
      file: git-ci/ci/tasks/deploy-stable.yml
      params:
        .: (( inject meta.task_connectivity_params ))
        DEPLOY_ENV:           (( concat "ci-" meta.iaas "-upgrade" ))
        KIT_SHORTNAME:        (( grab meta.kit ))
        SKIP_FRESH:           false
        SKIP_REPLACE_SECRETS: false
        SKIP_SMOKE_TESTS:     true
        SKIP_CLEAN:           true
    - task: upgrade
      file: git-ci/ci/tasks/upgrade.yml
      params:
        .: (( inject meta.task_connectivity_params ))
        DEPLOY_ENV:           (( concat "ci-" meta.iaas "-upgrade" ))
        KIT_SHORTNAME:        (( grab meta.kit ))
        SKIP_FRESH:           true
        SKIP_REPLACE_SECRETS: true
        SKIP_SMOKE_TESTS:     false
        SKIP_CLEAN:           false
    on_failure:
      put: notify
      params:
        topic:   (( concat meta.shout.topic "-$BUILD_JOB_NAME" ))
        message: tests job '$BUILD_JOB_NAME' failed.
        ok:      no
        link:    (( grab meta.shout.links.build ))
