#!/bin/bash

export BAT_STEMCELL="$(pwd)/vsphere-stemcell/stemcell.tgz"
export BAT_DEPLOYMENT_SPEC="$(pwd)/git-ci/ci/tasks/bats/bats.yml"
export BAT_BOSH_CLI=bosh
# DNS host or IP where BOSH-controlled PowerDNS server is running, which is required for the DNS tests. For example, if BAT is being run against a MicroBOSH then this value will be the same as BAT_DIRECTOR
export BAT_DNS_HOST=10.128.9.32
export BAT_INFRASTRUCTURE=vsphere
export BAT_NETWORKING=manual

# the path to ssh key, used by OS specs to ssh into BOSH VMs
export BAT_PRIVATE_KEY="$(pwd)/dummy"
export BOSH_OS_BATS=false

export BOSH_ENVIRONMENT=https://10.128.9.32:25555

safe target da-vault "$VAULT_URI" -k
echo "$VAULT_TOKEN" | safe auth token
safe read secret/handshake

export BOSH_CA_CERT=$(safe read secret/ci/bats/bosh/ssl/ca:certificate)
export BOSH_CLIENT=admin
export BOSH_CLIENT_SECRET=$(safe read secret/ci/bats/bosh/users/admin:password)

gem install bundler
cd bats
bundle install
# NOTE!: adding tags will exlude component.
bundle exec rspec spec \
  --tag ~vip_networking \
  --tag ~dynamic_networking \
  --tag ~root_partition \
  --tag ~raw_ephemeral_storage \
  --tag ~multiple_manual_networks
